language: python
python:
  #TODO: Add more versions to grid (including Py2.7 which requires use of six probably)
  #TODO: Like above (just testing travis :-)
  - "3.5"

env:
  global:
    - GH_REF: github.com/jacekszubert/meme-maker.git

install: "pip install -r requirements/test.txt"

script: python setup.py test
